# Generated by Django 5.0.6 on 2024-07-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balanceCode", models.CharField(max_length=10)),
                ("Amount", models.IntegerField()),
                ("Type", models.CharField(max_length=100)),
                ("BalanceComment", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("emplID", models.AutoField(primary_key=True, serialize=False)),
                ("internalID", models.IntegerField()),
                ("externalID", models.IntegerField()),
                ("prefix", models.CharField(max_length=10)),
                ("First_Name", models.CharField(max_length=100)),
                ("Last_Name", models.CharField(max_length=100)),
                ("HireDate", models.DateField()),
                ("Status", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Titles",
            fields=[
                ("titleCode", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=97)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Balance_Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balanceCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.balances",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="balances",
            name="emplID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.employees"
            ),
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "jobNum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Location", models.CharField(max_length=256)),
                ("JobType", models.CharField(max_length=256)),
                ("Flag", models.CharField(max_length=1000)),
                ("Note", models.CharField(max_length=500)),
                (
                    "AssignedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.employees",
                    ),
                ),
                (
                    "EligibleTitles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.titles"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employees",
            name="JobNum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.jobs"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="titleCode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.titles"
            ),
        ),
    ]
